AWSTemplateFormatVersion: 2010-09-09



Parameters:

  ZipCodeBucketName:

    Type: String

    Description: Bucket ARN where function zip file is stored



  ZipCodeFileName:

    Type: String

    Description: Name of lambda function zip file with extension(i.e. lambdaCodeFunctions.zip)



  LambdaRate:

    Description: >

      The rate (frequency) that determines when CloudWatch Events runs the rule that

      triggers the Lambda function.

    Default: rate(2 days)

    AllowedValues:

      - rate(1 day)

      - rate(2 days)

      - rate(3 days)

    Type: String



Resources:

  lambdaNbRole:

    Type: 'AWS::IAM::Role'

    Properties:

      RoleName: lambda-sm-automation-role

      AssumeRolePolicyDocument:

        Version: 2012-10-17

        Statement:

          - Effect: Allow

            Principal:

              Service:

                - lambda.amazonaws.com

            Action:

              - 'sts:AssumeRole'

      ManagedPolicyArns:

        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Path: /

      Policies:

        - PolicyName: LmabdaSagemakerFullAccess

          PolicyDocument:

            Version: 2012-10-17

            Statement:

              - Effect: Allow

                Action:

                  - 'sagemaker:*'

                Resource: '*'

      

        - PolicyName: LmabdaS3Access

          PolicyDocument:

            Version: 2012-10-17

            Statement:

              - Effect: Allow

                Action:

                  - 's3:*'

                Resource: '*'



  SmAutomationLambdaFunction:

    DependsOn: lambdaNbRole

    Type: AWS::Lambda::Function

    Properties:

      Code:

        S3Bucket: !Sub '${ZipCodeBucketName}'

        S3Key: !Sub '${ZipCodeFileName}'

      Runtime: python3.7

      Handler: lambda_function.lambda_handler

      Timeout: 900

      Role: !GetAtt lambdaNbRole.Arn

      FunctionName: "ews-sagemaker-automation" 



  SmLambdaSchedule:

    DependsOn: SmAutomationLambdaFunction

    Type: "AWS::Events::Rule"

    Properties:

      Description: >

        A schedule for the Lambda function..

      ScheduleExpression: !Ref LambdaRate

      State: ENABLED

      Targets:

        - Arn: !Sub ${SmAutomationLambdaFunction.Arn}

          Id: LambdaSchedule

    

  LambdaSchedulePermission:

    DependsOn: SmAutomationLambdaFunction

    Type: "AWS::Lambda::Permission"

    Properties:

      Action: 'lambda:InvokeFunction'

      FunctionName: !Sub ${SmAutomationLambdaFunction.Arn}

      Principal: 'events.amazonaws.com'

      SourceArn: !Sub ${SmLambdaSchedule.Arn}

